### ISSUE TITLE
raise target validation errors when name property is empty

### ISSUE THREAD

**Issue by luizyao** [luizyao/pytest-pyppeteer#2]
Create more than one `target` in `pyproject.toml`, but now only use first one, others used in future.

When execute `pytest`, raise validation errors:

![图片](https://user-images.githubusercontent.com/30592265/90609320-72c75980-e236-11ea-9d71-2df828de5e67.png)

**Comment by luizyao** [comment]
`pytest-pyppeteer` will validate `name` is not empty, and match file name in `desc` folder. Then validate matched `desc` file MUST exist `[HomePage]`.

**Comment by luizyao** [comment]
I will fix this issue to ignore to create target which missing name or name is empty.

```toml
[tool.pytest.pyppeteer.targets.target2]
name = ""
base_url = ""
```

or 

```toml
[tool.pytest.pyppeteer.targets.target2]
base_url = ""
```
