### ISSUE TITLE
Keep a `CHANGES` file?

### ISSUE THREAD

**Issue by tony** [luizyao/pytest-pyppeteer#34]
Format idea, `CHANGES`

```markdown
# Changelog

## pytest-pyppeteer  0.3.1 - unreleased

- _Insert changes/features/fixes for next release here_

### Maintenance

- #32: docs: Add project description

## pytest-pyppeteer 0.3.0 (2022-01-27)

### Packaging

- Remove `Pipfile.lock`

### What's new

- Upgrade pyppeteer 0.2.3 -> 0.2.5 (#23)

### Documentation

- Document `--slow`

## pytest-pyppeteer 0.2.1 (2020-10-16)

<!---
# vim: set filetype=markdown:
-->

```

Then if you like #33 

```toml
[tool.poetry.urls]
# ... the rest
Changes = "https://github.com/luizyao/pytest-pyppeteer/blob/master/CHANGES"
```
